[Feature/chungchun-34] S3 버킷 생성 + 프로필 이미지 업로드 API + cors 설정
ArtTalkTalk/ArtTalkTalk_backend pull request #3
Opened 2024-01-26 12:55 UTC by thisishwan2

### ✅ PR 타입 & 티켓번호
feature (#34)

### 📌 작업사항
- s3 환경변수 설정
- aws s3 cors, 권한 설정
- 이미지 업로드 컨트롤러, 서비스 생성
- 이미지 엔티티, 레포지토리 생성
- 테스트 DB 생성(h2)

### 🔥 리뷰어가 참고할 사항
- 터미널에서 아래의 명령어로 yml 최신화 시켜주시면 될것 같습니다.
`git submodule update --remote config`
- 추가로 spring configuration을 edit 하셔셔 profile을 test 로 설정하시면 h2 DB와 연결됩니다!

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/common/s3/S3Config.java
> +    private String region;
Construtor Binding을 사용해보는건 어떨까요? 제가 생각했을 때 좋은 점은 아래와 같아요
1. 불변의 이득을 가져갈 수 있음
2. cloud.aws.~~을 반복하지 않아도 됨
3. @Value는 변수가 여기저기 흩어진 반면, 하나의 클래스로 관리하기 때문에 응집도가 높음
참고: https://mangkyu.tistory.com/189

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/common/db/TestDbConfig.java
> +}
Spring Boot에서는 Auto Configuration으로 Datasource를 자동으로 만들어 넣어주는 기능을 갖고 있어요
dev 환경도 있을텐데 그 때마다 환경설정 Bean을 만드는 방식은 코드 응집도가 낮아보여요 
DB와 같은 외부 환경 변수 관리는 yaml파일로 해보는게 어떨까요?

yaml파일로 추출한다면 이런 느낌이예요

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:~/youth_test
    username: sa
    password:

2024-01-26 13:54 UTC, arsgsg1 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
jpa를 사용하는데 jdbc 의존성이 들어갈 이유가 있나용?

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/image/controller/ImageController.java
> +@RequestMapping("/v1/images")
저희가 앱 환경이라면 버저닝이 의미가 있지만 웹 환경이라 배포 후 호환성을 고려하지 않아도 될 것 같아서 /v1/~ 과 같은 prefix는 불필요해보여요

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/image/entity/Image.java
> +public class Image {
이건 제 개인 취향일 수도 있는데 저는 도메인 객체와의 구별을 위해 엔티티 클래스엔 ~~Entity라는 postfix를 붙여서 써요
이런 느낌의 네이밍은 어떨까요?

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/image/repository/ImageRepository.java
> +}
요거 @Repository 어노테이션이 빠져있어용

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/common/s3/FileNameBuildUtils.java
> +        return dirName + "/" + fileName + "_" + now + fileExtension;
원본 파일 이름을 그대로 업로드해야 하는 상황이 없다면 UUID로 매핑해보는게 어떨까요? 만약 한글같은게 들어가면 유니코드를 지원안하는 상황에서 오류가 발생할 수도 있을 것 같아요
파일 이름을 짓는 역할을 유틸 클래스에 위임했는데, 다형성을 이용해보는건 어떨까요?
FileNameGenerator와 같은 인터페이스를 만들어서 buildFileName 메서드를 두고, 구현체에서 책임을 갖게 하면 추후 이름 짓는 룰이 변경된다는 상황이 왔을 때 유연하게 대처할 수 있을 것 같아요 테스트하기도 쉬워지구요

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +    }
저희가 지금은 S3를 사용한다지만 "파일 업로드"에 대한 행위 자체는 추상화할 수 있어보여요
예를 들어 
`interface FileUploader {
  public String uploadFile(MultipartFile file, String dirName)
}
`
이런 인터페이스를 두고 구현체로 S3FileUploader 클래스라는 이름의 구현체로 책임을 위임하는게 어떨까요?

이렇게 했을 때의 장점은
1. 테스트가 쉬워져요
FileUploader를 사용하는 입장에서 AmazonS3Client나 private String bucket 변수에 값을 넣을 걱정을 안해도 돼요
2. 변경에는 닫혀있고 확장에는 열려있어요
S3가 아닌 다른 스토리지에 넣고 싶다면, 예를 들어 타 클라우드 서비스를 사용한다면 인터페이스 호출부는 그대로 두고, 구현체만 바꿔서 넣어줄 수 있기 때문에 좀 더 변경에 용이해요

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +                    .withCannedAcl(CannedAccessControlList.PublicRead));
Java는 I/O 상황에서 BufferdInputStream이라는 것도 제공해요 내부에 버퍼를 두고 읽어오는 방식인데, 네트워크 or 파일 I/O는 입출력 시간이 느리기 때문에 버퍼를 두고 최대한 덜 읽어오게끔하여 성능을 높일 수도 있어요

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +    public String uploadFile(MultipartFile multipartFile, String dirName) throws Exception {
버킷에 업로드하기 위한 디렉토리 이름도 yaml 파일로 관리하는게 어떨까요? 굳이 호출하는 입장에서 알 필요가 없을 것 같아요
게다가 문자열로 입력하기 때문에 오타 나기도 쉽구요
제가 생각한 방식은 이래요
1. uploadFile은 private로 두고 디렉토리 이름과 MultipartFile을 인자로 받아 S3에 구현만 한다
2. 외부에서 사용할 때는 uploadProfileImage와 같이 사용하는 곳에서 필요한 행위만 열어두고 yaml파일에서 디렉토리 이름을 끌어와 uploadFile에 전달한다

이 방식의 장점은 yaml 파일에 디렉토리 이름을 적어두었기 때문에 오타날 일이 없음, 추후 다른 이름의 디렉토리에 넣고 싶다면 uploadProfileImage 구현체에서 자체적으로 변경할 수 있기 때문에 유연함

2024-01-26 13:54 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/image/controller/ImageController.java
> +    @PostMapping("/upload")
행위가 url에 들어가는건 Restful하지 않아보여요 리소스 관점에서 생각해보면 어떨까요?
예를 들어 프로필 이미지 업로드면 url을 /images/profile로요

2024-01-26 13:55 UTC, arsgsg1 requested changes
리뷰 확인 부탁드려요~

2024-01-26 15:42 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/common/s3/S3Config.java
> +    private String region;
좋은 의견 감사합니다!
생성자 바인딩 방식으로 property주입 및 관리는 처음 안 내용이네요
해당 부분 수정하고 커밋올렸습니다👍🏻

2024-01-26 15:43 UTC, thisishwan2 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
아 이부분은 잘못 넣은것 같네요 다시 수정하겠습니다!

2024-01-26 15:45 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/common/db/TestDbConfig.java
> +}
해당 부분은 저도 보통 yml로 관리하는 편인데, 저번에 좌홍님과 DB 얘기했을때, 프로파일별로 DB 관리를 안하신다고(?) 이해를 했어서 위와 같은 방식으로 처리해 봤습니다!
아마 서로 미스 커넥션이 났었던것 같은데, 해당 부분은 다시 yml로 관리할 수 있도록 수정할게요!

2024-01-26 16:06 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/image/controller/ImageController.java
> +@RequestMapping("/v1/images")
확인했습니다!

2024-01-26 16:12 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/image/repository/ImageRepository.java
> +}
제가 알기로는 JpaRepository를 사용하면 @Repository가 이미 선언되어 있는 상태로 알고 있습니다.
혹시 명시적으로 눈에 보이게 하기 위해 어노테이션을 달자는 의견일까요??

2024-01-26 16:16 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/image/repository/ImageRepository.java
> +}
![image](https://github.com/final-project-temporaryName/youth_backend/assets/112103038/cb6aaabb-2bd6-4c1d-a4a3-6bbdf91da24b)
이와 같은 상속관계를 가지고 있는 것으로 알고 있습니다!

2024-01-26 16:16 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/image/entity/Image.java
> +public class Image {
아 네네 저는 이전에 도메인과 엔티티는 관점 차이라고 생각해서 크게 구분하지 않았는데, 구분해서 개발하는 것도 좋아보입니다!!

2024-01-26 16:18 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/image/repository/ImageRepository.java
> +}
아아 생각해보니 관습적으로 붙여서 없는게 이상하다 생각했었네요
사실 안 붙여도 상관은 없습니다. 말씀하신대로 명시적으로 눈에 잘 보이게하는 의도예요

2024-01-26 17:16 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/common/s3/FileNameBuildUtils.java
> +        return dirName + "/" + fileName + "_" + now + fileExtension;
파일 이름 자체를 UUID로 정의하자는 말씀이시죠?
이 부분은 말씀하신 오류가 있을 수도 있어서 동의합니다!
그리고 인터페이스와 구현체로 나누는 것도 좋은 의견인것 같습니다! 반영해놓겠습니다

2024-01-26 17:33 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/image/controller/ImageController.java
> +    @PostMapping("/upload")
아 이부분 저도 upload가 동사여서 고민을 했는데, 영문사전에 찾아보니까 upload가 명사로도 의미를 가지고 있어서 upload로 적긴했습니다. 근데 통상적으로 동사로 사용을 많이 하니까 좌홍님이 말씀하신대로 수정하는것도 좋아보이네요!
수정해보겠습니다

2024-01-26 17:48 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +    }
넵! 피드백 감사합니다,
반영완료했습니다!

2024-01-26 18:00 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +                    .withCannedAcl(CannedAccessControlList.PublicRead));
BufferdInputStream으로 성능 높히는 것을 고려해보지 못했네요.!
제가 궁금한점이 하나 있는데 BufferdInputStream로 할 경우에 버퍼 크기는 별도로 지정하시나요?

2024-01-26 18:05 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +    public String uploadFile(MultipartFile multipartFile, String dirName) throws Exception {
아 이부분은 현재는 이미지 업로드만 개발하지만, 이후에 파일 저장으로 바뀌는 경우를 고려해서 s3 dir을 지정할 수 있도록 설정한 부분입니다!
또한 이미지 업로드의 경우에도 현재는 작품에 대한 이미지만 다루지만, 향후에 추가 기능에 따라 s3에 업로드하는 파일에 따라 디렉토리로 구분하도록 호출할때 넣도록 했습니다.
혹시 이러한 경우에도 말씀하신 2번과 같이 구현을 하는게 나을까요??

2024-01-27 02:33 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +    public String uploadFile(MultipartFile multipartFile, String dirName) throws Exception {
아아 의도가 그러시다면 굳이 변경할 필요는 없어보여요

2024-01-27 02:34 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/s3/service/S3UploadService.java
> +                    .withCannedAcl(CannedAccessControlList.PublicRead));
별도로 지정해주지 않아도 디폴트로 설정된게 있어용

2024-01-27 02:38 UTC, arsgsg1 approved these changes

2024-01-27 02:38 UTC, arsgsg1 commented on src/main/java/org/example/youth_be/common/s3/FileNameBuildUtils.java
> +//        String fileName = originalFileName.substring(0, fileExtensionIndex);
요거 주석은 사용하지 않으면 삭제해주세용

2024-01-27 03:49 UTC, thisishwan2 commented on src/main/java/org/example/youth_be/common/s3/FileNameBuildUtils.java
> +//        String fileName = originalFileName.substring(0, fileExtensionIndex);
넵!

2024-01-27 03:58 UTC, merged